---
- name: Zabbix 5 LTS • Server + Web + Agent on every VM
  hosts: all                 # your AWX inventory is “vms”
  become: true
  gather_facts: true

  vars:
    # ── editable in an AWX Survey ──────────────────────────────
    zabbix_version:           "5.0"

    mysql_root_password:      "root_pw"          # ❶ keep only ONE line
    zabbix_db_password:       "StrongDBpass!"
    zabbix_admin_password:    "zabbix"
    php_timezone:             "Africa/Casablanca"

    # ── DB object names ────────────────────────────────────────
    zabbix_db_name:  zabbix
    zabbix_db_user:  zabbix

    # ── geerlingguy.mysql role tweaks ──────────────────────────
    mysql_flavor: mariadb
    mysql_packages: ['mariadb-server']
    mysql_daemon:   mariadb
    mysql_copy_mycnf: false           # ❷ skip /root/.my.cnf
    mysql_root_username: root
    mysql_root_password: "{{ mysql_root_password }}"

    mysql_databases:
      - name: "{{ zabbix_db_name }}"
        encoding: utf8
        collation: utf8_bin

    mysql_users:
      - name: "{{ zabbix_db_user }}"
        host: localhost
        password: "{{ zabbix_db_password }}"
        priv: "{{ zabbix_db_name }}.*:ALL"

    # ── dj-wasabi.zabbix-server ───────────────────────────────
    zabbix_server_version:        "{{ zabbix_version }}"
    zabbix_server_database_long:  mysql
    zabbix_server_dbname:         "{{ zabbix_db_name }}"
    zabbix_server_dbuser:         "{{ zabbix_db_user }}"
    zabbix_server_dbpassword:     "{{ zabbix_db_password }}"
    zabbix_database_sqlload:      true
    zabbix_api_create_user:       true
    zabbix_api_login_user:        Admin
    zabbix_api_login_pass:        "{{ zabbix_admin_password }}"

    # ── dj-wasabi.zabbix-web ──────────────────────────────────
    zabbix_web_version:  "{{ zabbix_version }}"
    zabbix_web_timezone: "{{ php_timezone }}"
    zabbix_web_language: en_US

    # ── dj-wasabi.zabbix-agent (local agent) ─────────────────
    zabbix_agent_server:       127.0.0.1
    zabbix_agent_serveractive: 127.0.0.1

  roles:
    - geerlingguy.mysql
    - dj-wasabi.zabbix-server
    - dj-wasabi.zabbix-web
    - dj-wasabi.zabbix-agent
