---
- name: Install and configure Zabbix 5.0 LTS (MySQL/MariaDB)
  hosts: all
  become: true
  gather_facts: true

  collections:
    - community.mysql          # mysql_db / mysql_user / mysql_query

  vars:
    zabbix_version: "5.0"

    zabbix_db_name: zabbix
    zabbix_db_user: zabbix
    zabbix_db_pass: zabbix_password   # ← vault / override for prod

    php_timezone: Africa/Casablanca

    # Debian/Ubuntu repo-key paths
    zbx_key_url:  https://repo.zabbix.com/zabbix-official-repo.key
    zbx_key_asc:  /usr/share/keyrings/zabbix.asc
    zbx_keyring: /usr/share/keyrings/zabbix.gpg

  tasks:
  # ------------------------------------------------------------------
  # Repositories & signing keys
  # ------------------------------------------------------------------
  - name: Add Zabbix repo (RHEL family)
    ansible.builtin.yum:
      name: >-
        https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/
        {{ ansible_distribution_major_version }}/x86_64/
        zabbix-release-{{ zabbix_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
    when: ansible_os_family == "RedHat"

  - name: Enable EPEL (RHEL family)
    ansible.builtin.yum:
      name: epel-release
      state: present
    when: ansible_os_family == "RedHat"

  - name: Ensure gnupg present (Debian/Ubuntu)
    ansible.builtin.apt:
      name: gnupg
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  - name: Map Ubuntu codename → Zabbix-supported series
    ansible.builtin.set_fact:
      zbx_ubuntu_series: "{{ {'jammy':'jammy','focal':'focal','bionic':'bionic'}
                             .get(ansible_distribution_release,'jammy') }}"
    when: ansible_os_family == "Debian"

  - name: Download Zabbix ASCII key
    ansible.builtin.get_url:
      url: "{{ zbx_key_url }}"
      dest: "{{ zbx_key_asc }}"
      mode: "0644"
    when: ansible_os_family == "Debian"

  - name: Convert key to keyring
    ansible.builtin.command:
      cmd: "gpg --dearmor -o {{ zbx_keyring }} {{ zbx_key_asc }}"
    args:
      creates: "{{ zbx_keyring }}"
    when: ansible_os_family == "Debian"

  - name: Add Zabbix APT repo
    ansible.builtin.apt_repository:
      repo: >-
        deb [arch=amd64 signed-by={{ zbx_keyring }}]
        https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu
        {{ zbx_ubuntu_series }} main
      filename: zabbix
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  # ------------------------------------------------------------------
  # OS-specific paths / package names
  # ------------------------------------------------------------------
  - name: Set distro-specific variables
    ansible.builtin.set_fact:
      zbx_frontend_pkg: "{{ 'zabbix-web-mysql' if ansible_os_family == 'RedHat'
                                            else 'zabbix-frontend-php' }}"
      zbx_web_srv:      "{{ 'httpd' if ansible_os_family == 'RedHat'
                                     else 'apache2' }}"
      zbx_apache_conf:  "{{ '/etc/httpd/conf.d/zabbix.conf'
                            if ansible_os_family == 'RedHat'
                            else '/etc/apache2/conf-available/zabbix.conf' }}"
      mysql_socket:     "{{ '/var/lib/mysql/mysql.sock'
                            if ansible_os_family == 'RedHat'
                            else '/var/run/mysqld/mysqld.sock' }}"

  # ------------------------------------------------------------------
  # Install packages
  # ------------------------------------------------------------------
  - name: Install Zabbix server, agent & MariaDB
    ansible.builtin.package:
      name:
        - zabbix-server-mysql
        - "{{ zbx_frontend_pkg }}"
        - zabbix-agent
        - mariadb-server
        - "{{ 'python3-PyMySQL' if ansible_os_family == 'RedHat'
                                else 'python3-pymysql' }}"
      state: present
      update_cache: true

  # ------------------------------------------------------------------
  # MariaDB initialisation
  # ------------------------------------------------------------------
  - name: Ensure MariaDB running & enabled
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: true

  - name: Wait for MariaDB socket
    ansible.builtin.wait_for:
      path: "{{ mysql_socket }}"
      state: started
      timeout: 30

  - name: Create Zabbix database
    community.mysql.mysql_db:
      name: "{{ zabbix_db_name }}"
      state: present
      login_user: root
      login_unix_socket: "{{ mysql_socket }}"
      encoding: utf8
      collation: utf8_general_ci

  - name: Create Zabbix DB user (mysql_native_password)
    community.mysql.mysql_user:
      name: "{{ zabbix_db_user }}"
      host: localhost
      password: "{{ zabbix_db_pass }}"
      plugin: mysql_native_password
      priv: "{{ zabbix_db_name }}.*:ALL"
      state: present
      login_user: root
      login_unix_socket: "{{ mysql_socket }}"

  # ------------------------------------------------------------------
  # Import initial schema once
  # ------------------------------------------------------------------
  - name: Check if schema already loaded
    ansible.builtin.stat:
      path: "/var/lib/mysql/{{ zabbix_db_name }}/history.ibd"
    register: schema_present

  - name: Import Zabbix schema / images / data
    ansible.builtin.shell: |
      for f in schema.sql.gz images.sql.gz data.sql.gz; do
        gzip -dc "/usr/share/zabbix-server-mysql/$f" | \
          mysql --socket={{ mysql_socket }} -u root {{ zabbix_db_name }}
      done
    when: not schema_present.stat.exists
    args:
      creates: "/var/lib/mysql/{{ zabbix_db_name }}/history.ibd"

  - name: Verify table count ≥ 100
    community.mysql.mysql_query:
      login_user: root
      login_unix_socket: "{{ mysql_socket }}"
      login_db: "{{ zabbix_db_name }}"
      query: "SELECT COUNT(*) AS cnt FROM information_schema.tables WHERE table_schema='{{ zabbix_db_name }}';"
    register: tbl_cnt

  - name: Fail if schema still missing
    ansible.builtin.fail:
      msg: "Schema import failed — only {{ tbl_cnt.query_result[0]['cnt'] }} tables found."
    when: tbl_cnt.query_result[0]['cnt'] | int < 100

  # ------------------------------------------------------------------
  # Zabbix server configuration
  # ------------------------------------------------------------------
  - name: Configure /etc/zabbix/zabbix_server.conf
    ansible.builtin.blockinfile:
      path: /etc/zabbix/zabbix_server.conf
      marker: "# {mark} ANSIBLE MANAGED DB BLOCK"
      block: |
        DBHost=127.0.0.1
        DBPort=3306
        DBName={{ zabbix_db_name }}
        DBUser={{ zabbix_db_user }}
        DBPassword={{ zabbix_db_pass }}
    notify: restart zabbix-server

  # ------------------------------------------------------------------
  # PHP front-end timezone
  # ------------------------------------------------------------------
  - name: Ensure PHP timezone in Apache conf
    ansible.builtin.lineinfile:
      path: "{{ zbx_apache_conf }}"
      regexp: '^php_value +date.timezone'
      line: "php_value date.timezone {{ php_timezone }}"
    notify: restart webserver
    when: ansible.builtin.stat(path=zbx_apache_conf).stat.exists

  - name: Enable Apache Zabbix conf (Debian/Ubuntu)
    ansible.builtin.command: a2enconf zabbix
    when:
      - ansible_os_family == 'Debian'
      - ansible.builtin.stat(path=zbx_apache_conf).stat.exists
    notify: restart webserver

  # ------------------------------------------------------------------
  # Enable & start services
  # ------------------------------------------------------------------
  - name: Ensure web server is running
    ansible.builtin.service:
      name: "{{ zbx_web_srv }}"
      state: started
      enabled: true

  - name: Restart & enable Zabbix services
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop:
      - zabbix-server
      - zabbix-agent

  # ------------------------------------------------------------------
  # Handlers
  # ------------------------------------------------------------------
  handlers:
    - name: restart zabbix-server
      ansible.builtin.service:
        name: zabbix-server
        state: restarted

    - name: restart webserver
      ansible.builtin.service:
        name: "{{ zbx_web_srv }}"
        state: restarted
