---
- name: Install & configure Zabbix 5 LTS (MySQL/MariaDB)
  hosts: all
  become: true
  gather_facts: true

  collections:
    - community.mysql

  vars:
    # ── Zabbix version & DB credentials ────────────────────────
    zabbix_version: "5.0"

    zabbix_db_name: zabbix
    zabbix_db_user: zabbix
    zabbix_db_pass: zabbix_password        # ← vault / override in prod

    # fallback for hosts without debian-sys-maint file
    mysql_root_user: root
    mysql_root_password: ""                # set if root has a password

    php_timezone: Africa/Casablanca

    # Debian/Ubuntu key paths
    zbx_key_url:  https://repo.zabbix.com/zabbix-official-repo.key
    zbx_key_asc:  /usr/share/keyrings/zabbix.asc
    zbx_keyring: /usr/share/keyrings/zabbix.gpg

  tasks:
  # ────────────────────────────────────────────────────────────
  # 1.  Find a working admin account for MariaDB
  # ────────────────────────────────────────────────────────────
  - name: Does /etc/mysql/debian.cnf exist?
    stat:
      path: /etc/mysql/debian.cnf
    register: debian_cnf

  - name: Extract debian-sys-maint user
    shell: "awk '/^user/ {print $3; exit}' /etc/mysql/debian.cnf"
    register: debian_user
    when: debian_cnf.stat.exists
    changed_when: false

  - name: Extract debian-sys-maint password
    shell: "awk '/^password/ {print $3; exit}' /etc/mysql/debian.cnf"
    register: debian_pass
    when: debian_cnf.stat.exists
    changed_when: false

  - name: Set admin connection facts
    set_fact:
      admin_user: "{{ (debian_user.stdout | default('')).strip() | ternary(debian_user.stdout, mysql_root_user) }}"
      admin_pass: "{{ (debian_pass.stdout | default('')).strip() | ternary(debian_pass.stdout, mysql_root_password) }}"

  # helper var for CLI
  - name: Compose mysql CLI prefix
    set_fact:
      mysql_cli: >-
        mysql --protocol=socket
        -u{{ admin_user }}
        {{ '-p' ~ admin_pass if admin_pass|length > 0 else '' }}

  # ────────────────────────────────────────────────────────────
  # 2.  Add Zabbix repositories (unchanged logic)
  # ────────────────────────────────────────────────────────────
  - name: Add Zabbix repo (RHEL)
    yum:
      name: >-
        https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/
        {{ ansible_distribution_major_version }}/x86_64/
        zabbix-release-{{ zabbix_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
    when: ansible_os_family == "RedHat"

  - name: Enable EPEL (RHEL)
    yum:
      name: epel-release
      state: present
    when: ansible_os_family == "RedHat"

  - name: Ensure gnupg (Debian/Ubuntu)
    apt:
      name: gnupg
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  - name: Map Ubuntu codename → supported series
    set_fact:
      zbx_ubuntu_series: "{{ {'jammy':'jammy','focal':'focal','bionic':'bionic'}
                             .get(ansible_distribution_release,'jammy') }}"
    when: ansible_os_family == "Debian"

  - name: Download Zabbix ASCII key
    get_url:
      url:  "{{ zbx_key_url }}"
      dest: "{{ zbx_key_asc }}"
      mode: "0644"
    when: ansible_os_family == "Debian"

  - name: Convert key to keyring
    command:
      cmd: "gpg --dearmor -o {{ zbx_keyring }} {{ zbx_key_asc }}"
    args:
      creates: "{{ zbx_keyring }}"
    when: ansible_os_family == "Debian"

  - name: Add Zabbix APT repository
    apt_repository:
      repo: >-
        deb [arch=amd64 signed-by={{ zbx_keyring }}]
        https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu
        {{ zbx_ubuntu_series }} main
      filename: zabbix
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  # ────────────────────────────────────────────────────────────
  # 3.  Package installation & path variables
  # ────────────────────────────────────────────────────────────
  - name: OS-specific variables
    set_fact:
      zbx_frontend_pkg: "{{ 'zabbix-web-mysql' if ansible_os_family == 'RedHat'
                                            else 'zabbix-frontend-php' }}"
      zbx_web_srv:      "{{ 'httpd' if ansible_os_family == 'RedHat'
                                     else 'apache2' }}"
      zbx_apache_conf:  "{{ '/etc/httpd/conf.d/zabbix.conf'
                            if ansible_os_family == 'RedHat'
                            else '/etc/apache2/conf-available/zabbix.conf' }}"
      mysql_socket:     "{{ '/var/lib/mysql/mysql.sock'
                            if ansible_os_family == 'RedHat'
                            else '/var/run/mysqld/mysqld.sock' }}"

  - name: Install Zabbix server, agent & MariaDB
    package:
      name:
        - zabbix-server-mysql
        - "{{ zbx_frontend_pkg }}"
        - zabbix-agent
        - mariadb-server
        - "{{ 'python3-PyMySQL' if ansible_os_family == 'RedHat'
                                else 'python3-pymysql' }}"
      state: present
      update_cache: true

  # ────────────────────────────────────────────────────────────
  # 4.  MariaDB initialisation
  # ────────────────────────────────────────────────────────────
  - name: Ensure MariaDB started & enabled
    service:
      name: mariadb
      state: started
      enabled: true

  - name: Wait for socket
    wait_for:
      path: "{{ mysql_socket }}"
      state: started
      timeout: 30

  - name: Create DB & user (idempotent)
    shell: |
      {{ mysql_cli }} <<'SQL'
      CREATE DATABASE IF NOT EXISTS {{ zabbix_db_name }}
        CHARACTER SET utf8 COLLATE utf8_bin;
      CREATE USER IF NOT EXISTS '{{ zabbix_db_user }}'@'localhost'
        IDENTIFIED WITH mysql_native_password BY '{{ zabbix_db_pass }}';
      GRANT ALL PRIVILEGES ON {{ zabbix_db_name }}.* TO
        '{{ zabbix_db_user }}'@'localhost';
      FLUSH PRIVILEGES;
      SQL
    args:
      executable: /bin/bash

  # ────────────────────────────────────────────────────────────
  # 5.  Import Zabbix schema - only once
  # ────────────────────────────────────────────────────────────
  - name: Schema already there?
    stat:
      path: "/var/lib/mysql/{{ zabbix_db_name }}/history.ibd"
    register: schema_present

  - name: Import schema, images, data
    shell: |
      for f in schema.sql.gz images.sql.gz data.sql.gz; do
        gzip -dc /usr/share/zabbix-server-mysql/$f | {{ mysql_cli }} {{ zabbix_db_name }}
      done
    when: not schema_present.stat.exists
    args:
      executable: /bin/bash
      creates: "/var/lib/mysql/{{ zabbix_db_name }}/history.ibd"

  # ────────────────────────────────────────────────────────────
  # 6.  Verify ≥100 tables  (PyMySQL via zabbix user)
  # ────────────────────────────────────────────────────────────
  - name: Count tables
    community.mysql.mysql_query:
      login_user: "{{ zabbix_db_user }}"
      login_password: "{{ zabbix_db_pass }}"
      login_host: 127.0.0.1
      login_db: "{{ zabbix_db_name }}"
      query: |
        SELECT COUNT(*) AS cnt
        FROM information_schema.tables
        WHERE table_schema='{{ zabbix_db_name }}';
    register: tbl_cnt

  - name: Fail if schema missing
    fail:
      msg: "Schema import failed — only {{ tbl_cnt.query_result[0]['cnt'] }} tables found."
    when: tbl_cnt.query_result[0]['cnt'] | int < 100

  # ────────────────────────────────────────────────────────────
  # 7.  Zabbix server configuration
  # ────────────────────────────────────────────────────────────
  - name: Configure zabbix_server.conf
    blockinfile:
      path: /etc/zabbix/zabbix_server.conf
      marker: "# {mark} ANSIBLE MANAGED DB BLOCK"
      block: |
        DBHost=127.0.0.1
        DBPort=3306
        DBName={{ zabbix_db_name }}
        DBUser={{ zabbix_db_user }}
        DBPassword={{ zabbix_db_pass }}
    notify: restart zabbix-server

  # ────────────────────────────────────────────────────────────
  # 8.  Apache front-end (timezone)
  # ────────────────────────────────────────────────────────────
  - name: Ensure PHP timezone in Apache conf
    lineinfile:
      path: "{{ zbx_apache_conf }}"
      regexp: '^php_value +date.timezone'
      line:  "php_value date.timezone {{ php_timezone }}"
    notify: restart webserver
    when: stat(path=zbx_apache_conf).stat.exists

  - name: Enable Apache Zabbix conf (Debian/Ubuntu)
    command: a2enconf zabbix
    when:
      - ansible_os_family == 'Debian'
      - stat(path=zbx_apache_conf).stat.exists
    notify: restart webserver

  # ────────────────────────────────────────────────────────────
  # 9.  Start / enable services
  # ────────────────────────────────────────────────────────────
  - name: Ensure web server is running
    service:
      name: "{{ zbx_web_srv }}"
      state: started
      enabled: true

  - name: Restart & enable Zabbix services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop:
      - zabbix-server
      - zabbix-agent

  # ────────────────────────────────────────────────────────────
  # 10. Handlers
  # ────────────────────────────────────────────────────────────
  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart webserver
      service:
        name: "{{ zbx_web_srv }}"
        state: restarted
