---
- name: Install and configure Zabbix
  hosts: all
  become: yes

  # Tell Ansible up-front which extra collection we need
  collections:
    - community.mysql

  vars:
    zabbix_db_name: zabbix
    zabbix_db_user: zabbix
    zabbix_db_pass: zabbix_password
    php_timezone: Africa/Casablanca   # change if you’re in a different zone

  tasks:
    # ---------------------------------------------------------------------
    # Package installation
    # ---------------------------------------------------------------------
    - name: Enable EPEL (needed for PyMySQL on RHEL/CentOS 7)
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install Zabbix repository
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

    - name: Install Zabbix server, frontend and agent
      ansible.builtin.yum:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-agent
        state: present

    - name: Install MariaDB server and Python DB bindings
      ansible.builtin.yum:
        name:
          - mariadb-server
          - python3-PyMySQL          # community.mysql needs a driver
        state: present

    # ---------------------------------------------------------------------
    # Database setup
    # ---------------------------------------------------------------------
    - name: Start and enable MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create Zabbix database
      community.mysql.mysql_db:
        name: "{{ zabbix_db_name }}"
        state: present
        login_user: root

    - name: Create Zabbix DB user
      community.mysql.mysql_user:
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_pass }}"
        priv: "{{ zabbix_db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root

    - name: Import initial schema and data
      ansible.builtin.command: >
        bash -c "gunzip -c $(ls /usr/share/doc/zabbix-server-mysql*/create.sql.gz) |
                 mysql -u {{ zabbix_db_user }} -p{{ zabbix_db_pass }} {{ zabbix_db_name }}"
      args:
        creates: /var/lib/mysql/{{ zabbix_db_name }}/users.frm

    # ---------------------------------------------------------------------
    # Zabbix & web stack configuration
    # ---------------------------------------------------------------------
    - name: Configure Zabbix server DB password
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^#?DBPassword='
        line: "DBPassword={{ zabbix_db_pass }}"
      notify: Restart Zabbix server

    - name: Configure PHP timezone for Zabbix frontend
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: '^php_value date.timezone'
        line: "php_value date.timezone {{ php_timezone }}"
      notify: Restart Apache

    # ---------------------------------------------------------------------
    # Services
    # ---------------------------------------------------------------------
    - name: Start and enable Zabbix server
      ansible.builtin.service:
        name: zabbix-server
        state: started
        enabled: yes

    - name: Start and enable Zabbix agent
      ansible.builtin.service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Start and enable Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: Restart Zabbix server
      ansible.builtin.service:
        name: zabbix-server
        state: restarted

    - name: Restart Apache
      ansible.builtin.service:
        name: httpd
        state: restarted
