---
- name: Zabbix 5 LTS — server • web • agent (all-in-one VM)
  hosts: all
  become: true
  gather_facts: true

  vars:
    zabbix_version:        "5.0"
    mysql_root_password:   "root_pw"
    zabbix_db_password:    "StrongDBpass!"
    zabbix_admin_password: "zabbix"
    php_timezone:          "Africa/Casablanca"

    zabbix_db_name:  zabbix
    zabbix_db_user:  zabbix

  pre_tasks:
    # 0️⃣ Fix ownership of MariaDB datadir
    - name: Ensure /var/lib/mysql is owned by mysql:mysql
      file:
        path: /var/lib/mysql
        owner: mysql
        group: mysql
        recurse: true
      notify: restart mariadb

    # 1️⃣ Install packages (Debian shown; add yum block for RHEL if needed)
    - name: Install MariaDB + minimal web stack
      apt:
        name:
          - mariadb-server
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    # 2️⃣ Make sure MariaDB is running
    - name: Ensure MariaDB running
      service:
        name: mariadb
        state: started
        enabled: true

    # 3️⃣ Create Zabbix DB & user (idempotent)
    - name: Create DB & user if missing
      shell: |
        mysql --protocol=socket -uroot <<'EOSQL'
        CREATE DATABASE IF NOT EXISTS {{ zabbix_db_name }}
          CHARACTER SET utf8 COLLATE utf8_bin;
        CREATE USER IF NOT EXISTS '{{ zabbix_db_user }}'@'localhost'
          IDENTIFIED BY '{{ zabbix_db_password }}';
        GRANT ALL PRIVILEGES ON {{ zabbix_db_name }}.* TO
          '{{ zabbix_db_user }}'@'localhost';
        FLUSH PRIVILEGES;
        EOSQL
      args:
        executable: /bin/bash

  roles:
    - dj-wasabi.zabbix-server
    - dj-wasabi.zabbix-web
    - dj-wasabi.zabbix-agent

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
