- hosts: all
  become: yes
  tasks:
    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: yes



    - name: Install Docker from Snap
      ansible.builtin.command: snap install docker
      args:
        creates: /snap/bin/docker

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add ansible user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id | default(ansible_user) }}"
        groups: docker
        append: yes
