---
- name: Install & configure Zabbix 5 LTS (MariaDB + Apache/PHP)
  hosts: all
  become: true
  gather_facts: true

  vars:
    zabbix_version: "5.0"

    # —— DB credentials (change / vault in prod) ————————
    zabbix_db_name: zabbix
    zabbix_db_user: zabbix
    zabbix_db_pass: zabbix_password

    php_timezone: Africa/Casablanca

    # Key & repo paths
    zbx_key_url:  https://repo.zabbix.com/zabbix-official-repo.key
    zbx_keyring: /usr/share/keyrings/zabbix.gpg

    # Map any unknown codename to “jammy” (supported)
    zbx_series: |
      {% set c = ansible_facts.lsb.codename %}
      {{ c if c in ['jammy','focal','bionic'] else 'jammy' }}

  tasks:
  # ------------------------------------------------------------------
  # 1 — Repo key & repository (no apt-key, dearmored keyring file)
  # ------------------------------------------------------------------
  - name: Prerequisites for HTTPS APT
    apt:
      name: [gnupg, ca-certificates, lsb-release, curl]
      state: present
      update_cache: true

  - name: Download & dearmor Zabbix key
    shell: |
      curl -fsSL "{{ zbx_key_url }}" | gpg --dearmor -o "{{ zbx_keyring }}"
    args:
      creates: "{{ zbx_keyring }}"

  - name: Add Zabbix APT repository
    apt_repository:
      repo: >-
        deb [arch=amd64 signed-by={{ zbx_keyring }}]
        https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu
        {{ zbx_series }} main
      filename: zabbix
      state: present
      update_cache: true

  # ------------------------------------------------------------------
  # 2 — Install packages
  # ------------------------------------------------------------------
  - name: Install Zabbix server, agent, MariaDB, Apache & PHP
    apt:
      name:
        - zabbix-server-mysql
        - zabbix-frontend-php
        - zabbix-agent
        - mariadb-server
        - libapache2-mod-php
        - php-mysql
      state: present
      update_cache: true

  # ------------------------------------------------------------------
  # 3 — Create DB & user (root socket login, no password)
  # ------------------------------------------------------------------
  - name: Ensure MariaDB running
    service:
      name: mariadb
      state: started
      enabled: true

  - name: Create database and user
    shell: |
      mysql --protocol=socket <<'EOSQL'
      CREATE DATABASE IF NOT EXISTS {{ zabbix_db_name }}
        CHARACTER SET utf8 COLLATE utf8_bin;
      CREATE USER IF NOT EXISTS '{{ zabbix_db_user }}'@'localhost'
        IDENTIFIED BY '{{ zabbix_db_pass }}';
      GRANT ALL PRIVILEGES ON {{ zabbix_db_name }}.* TO
        '{{ zabbix_db_user }}'@'localhost';
      FLUSH PRIVILEGES;
      EOSQL
    args:
      executable: /bin/bash

  # ------------------------------------------------------------------
  # 4 — Import schema (one-time)
  # ------------------------------------------------------------------
  - name: Schema already present?
    stat:
      path: "/var/lib/mysql/{{ zabbix_db_name }}/history.ibd"
    register: schema_flag

  - name: Import Zabbix schema, images, data
    shell: |
      for f in schema.sql.gz images.sql.gz data.sql.gz; do
        zcat "/usr/share/zabbix-server-mysql/$f" | mysql {{ zabbix_db_name }}
      done
    when: not schema_flag.stat.exists
    args:
      executable: /bin/bash

  # ------------------------------------------------------------------
  # 5 — Configure zabbix_server.conf
  # ------------------------------------------------------------------
  - name: Write DB settings
    blockinfile:
      path: /etc/zabbix/zabbix_server.conf
      marker: "# {mark} ANSIBLE MANAGED DB BLOCK"
      block: |
        DBHost=127.0.0.1
        DBName={{ zabbix_db_name }}
        DBUser={{ zabbix_db_user }}
        DBPassword={{ zabbix_db_pass }}
    notify: restart zabbix-server

  # ------------------------------------------------------------------
  # 6 — Set PHP timezone & enable Apache site
  # ------------------------------------------------------------------
  - name: Ensure PHP timezone
    lineinfile:
      path: /etc/zabbix/apache.conf
      regexp: '^php_value +date.timezone'
      line:  "php_value date.timezone {{ php_timezone }}"
    notify: restart apache2

  - name: Enable Zabbix Apache config
    command: a2enconf zabbix
    args:
      creates: /etc/apache2/conf-enabled/zabbix.conf
    notify: restart apache2

  # ------------------------------------------------------------------
  # 7 — Start / enable services
  # ------------------------------------------------------------------
  - name: Enable and start core services
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - zabbix-server
      - zabbix-agent
      - apache2

  # ------------------------------------------------------------------
  # 8 — Handlers
  # ------------------------------------------------------------------
  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted
