---
- name: Zabbix 5 LTS — server • web • agent (all-in-one VM)
  hosts: all            # AWX inventory “vms”
  become: true
  gather_facts: true

  vars:
    # ── editable via AWX Survey (one copy only) ──────────────────
    zabbix_version:         "5.0"

    mysql_root_password:    "root_pw"
    zabbix_db_password:     "StrongDBpass!"
    zabbix_admin_password:  "zabbix"
    php_timezone:           "Africa/Casablanca"

    zabbix_db_name:  zabbix
    zabbix_db_user:  zabbix

  pre_tasks:
    # 0️⃣ ensure needed pkgs (Debian example; add yum block for RHEL if used) —
    - name: Install MariaDB + minimal PHP stack
      apt:
        name:
          - mariadb-server
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    # 1️⃣ stop mariadb, fix datadir perms, start again ————————————
    - name: Stop MariaDB before fixing permissions
      service:
        name: mariadb
        state: stopped

    - name: Ensure /var/lib/mysql owned by mysql:mysql and mode 0755
      file:
        path: /var/lib/mysql
        owner: mysql
        group: mysql
        mode: "0755"

    - name: Start & enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    # 2️⃣ create DB + user (idempotent) ————————————————————————
    - name: Create zabbix database and user (socket login)
      shell: |
        mysql --protocol=socket -uroot <<'EOSQL'
        CREATE DATABASE IF NOT EXISTS {{ zabbix_db_name }}
          CHARACTER SET utf8 COLLATE utf8_bin;
        CREATE USER IF NOT EXISTS '{{ zabbix_db_user }}'@'localhost'
          IDENTIFIED BY '{{ zabbix_db_password }}';
        GRANT ALL PRIVILEGES ON {{ zabbix_db_name }}.* TO
          '{{ zabbix_db_user }}'@'localhost';
        FLUSH PRIVILEGES;
        EOSQL
      args:
        executable: /bin/bash

  roles:
    - dj-wasabi.zabbix-server   # loads schema, configures server
    - dj-wasabi.zabbix-web      # front-end & PHP TZ
    - dj-wasabi.zabbix-agent    # local agent

  post_tasks:
    - name: Zabbix URL & default login
      debug:
        msg: >
          Zabbix UI → http://{{ ansible_default_ipv4.address }}/zabbix
          • Login: Admin / {{ zabbix_admin_password }}

