---
- name: Zabbix 5 LTS — server • web • agent (all-in-one VM)
  hosts: all            # AWX inventory “vms”
  become: true
  gather_facts: true

  vars:
    # ── secrets you’ll override via an AWX Survey ────────────────
    zabbix_version:        "5.0"

    mysql_root_password:   "root_pw"
    zabbix_db_password:    "StrongDBpass!"
    zabbix_admin_password: "zabbix"
    php_timezone:          "Africa/Casablanca"

    zabbix_db_name:  zabbix
    zabbix_db_user:  zabbix

    # ── REQUIRED: GPG key map with *string* index "50" ───────────
    zabbix_repo_gpg_key:
      '50': '082AB56BA14FE591'      # ← quoted ‟50” fixes the lookup error

  pre_tasks:
    - name: Install MariaDB + minimal PHP stack (Debian/Ubuntu)
      apt:
        name:
          - mariadb-server
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Stop MariaDB before fixing perms
      service:
        name: mariadb
        state: stopped

    - name: Ensure /var/lib/mysql owned by mysql:mysql
      file:
        path: /var/lib/mysql
        owner: mysql
        group: mysql
        mode: '0755'

    - name: Start & enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Create Zabbix database and user (idempotent)
      shell: |
        mysql --protocol=socket -uroot <<'EOSQL'
        CREATE DATABASE IF NOT EXISTS {{ zabbix_db_name }}
          CHARACTER SET utf8 COLLATE utf8_bin;
        CREATE USER IF NOT EXISTS '{{ zabbix_db_user }}'@'localhost'
          IDENTIFIED BY '{{ zabbix_db_password }}';
        GRANT ALL PRIVILEGES ON {{ zabbix_db_name }}.* TO
          '{{ zabbix_db_user }}'@'localhost';
        FLUSH PRIVILEGES;
        EOSQL
      args:
        executable: /bin/bash

  roles:
    - role: dj-wasabi.zabbix-server
      vars:
        zabbix_server_version:        "{{ zabbix_version }}"
        zabbix_server_database_long:  mysql
        zabbix_server_dbname:         "{{ zabbix_db_name }}"
        zabbix_server_dbuser:         "{{ zabbix_db_user }}"
        zabbix_server_dbpassword:     "{{ zabbix_db_password }}"
        zabbix_database_sqlload:      true
        zabbix_api_create_user:       true
        zabbix_api_login_user:        Admin
        zabbix_api_login_pass:        "{{ zabbix_admin_password }}"

    - role: dj-wasabi.zabbix-web
      vars:
        zabbix_web_version:           "{{ zabbix_version }}"
        zabbix_web_timezone:          "{{ php_timezone }}"
        zabbix_web_language:          en_US

    - role: dj-wasabi.zabbix-agent
      vars:
        zabbix_agent_server:          127.0.0.1
        zabbix_agent_serveractive:    127.0.0.1

  post_tasks:
    - name: Zabbix URL and login hint
      debug:
        msg: >
          Zabbix UI → http://{{ ansible_default_ipv4.address }}/zabbix
          • Login: Admin / {{ zabbix_admin_password }}
